# Generated by Django 4.0.4 on 2022-06-05 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_dospeli', models.FloatField(help_text=' Zadejte cenu za dospělého', verbose_name='Cena za dospělého')),
                ('cena_student', models.FloatField(help_text=' Zadejte cenu za studenta', verbose_name='Cena za studenta')),
                ('cena_dite', models.FloatField(help_text=' Zadejte cenu za dítě', verbose_name='Cena za dítě')),
                ('cena_duchodce', models.FloatField(help_text=' Zadejte cenu za důchodce', verbose_name='Cena za důchodce')),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osobni_telefon', models.IntegerField(help_text='Zadejte osobni telefon', null=True, unique=True, verbose_name='Osobni telefon')),
                ('sluzebni_telefon', models.IntegerField(help_text='Zadejte služební telefon', null=True, unique=True, verbose_name='Služební telefon')),
                ('email', models.CharField(help_text='Zadejte email', max_length=30, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSC', models.IntegerField(help_text='Zadejte PSČ', unique=True, verbose_name='poštovní směrovací číslo')),
                ('mesto', models.CharField(help_text='Zadejte název Města', max_length=150, verbose_name='Město')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('cislo_obcanskeho_prukazu', models.IntegerField(blank=True, help_text='Zadejte číslo ob. průkazu', primary_key=True, serialize=False, verbose_name='Číslo průkazu')),
                ('jmeno', models.CharField(help_text='Zadejte jméno', max_length=200, verbose_name='Jméno')),
                ('prijmeni', models.CharField(help_text='Zadejte příjmení', max_length=200, verbose_name='Příjmeni')),
                ('adresa', models.CharField(help_text='Zadejte adresu', max_length=200, verbose_name='Adresa')),
                ('osoba_bydliste', models.ManyToManyField(help_text='Přiřaďte město', to='hotel_reservation.mesto', verbose_name='město')),
                ('osoba_kontakt', models.ManyToManyField(help_text='Přiřaďte kontakt', to='hotel_reservation.kontakt', verbose_name='Kontakt')),
            ],
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poschodi', models.IntegerField(blank=True, help_text='Zadejte poschodí', verbose_name='Poschodí')),
                ('foto', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Fotografie')),
                ('cenik_pokoje', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='hotel_reservation.cenik')),
            ],
        ),
        migrations.CreateModel(
            name='Ubytovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubytovani_duchodce', models.IntegerField(blank=True, help_text='Zadejte počet ubytovaných důchodců', null=True, verbose_name='Důchodci')),
                ('ubytovani_student', models.IntegerField(blank=True, help_text='Zadejte počet ubytovaných studentů', null=True, verbose_name='Studenti')),
                ('ubytovani_dospeli', models.IntegerField(blank=True, help_text='Zadejte počet ubytovaných dospělých', null=True, verbose_name='Dospělí')),
                ('ubytovani_deti', models.IntegerField(blank=True, help_text='Zadejte počet ubytovaných dětí', null=True, verbose_name='Děti')),
            ],
        ),
        migrations.CreateModel(
            name='Vybaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(blank=True, choices=[('standard', 'standard'), ('nadstandard', 'nadstandard')], default='standard', help_text='Zvolte standard, nadstandard', max_length=20, verbose_name='Standard')),
                ('dvojluzka', models.IntegerField(blank=True, help_text='Zadejte počet jednolůžek na pokoji', null=True, verbose_name='Jednolůžka')),
                ('jednoluzka', models.IntegerField(blank=True, help_text='Zadejte počet dvojlůžek na pokoji', null=True, verbose_name='Dvojlůžka')),
                ('balkon', models.CharField(blank=True, choices=[('ano', 'ano'), ('ne', 'ne')], default='ne', help_text='Zvolte zda pokoj obsahuje balkon', max_length=5, verbose_name='Balkón')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_prijezdu', models.DateField(blank=True, help_text='Prosím použijte tenhle formát: <em>YYYY-MM-DD</em>.', verbose_name='Datum příjezdu')),
                ('pocet_noci', models.IntegerField(blank=True, help_text='Prosím zadejte počet nocí v celém čísle', verbose_name='Počet nocí')),
                ('cas_vyhotoveni', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 18, 37, 0, 593669), help_text='Prosím zadejte čas vyhodnocení', null=True, verbose_name='Čas vyhotovení')),
                ('osoba_cislo_obcanskeho_prukazu', models.ManyToManyField(help_text='Zadejte cislo prukazu', to='hotel_reservation.osoba')),
                ('pokoj', models.ManyToManyField(help_text='Zadejte číslo pokoje', to='hotel_reservation.pokoj', verbose_name='přiřaďte pokoj')),
                ('ubytovani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_reservation.ubytovani')),
            ],
        ),
        migrations.AddField(
            model_name='pokoj',
            name='vybaveni_pokoje',
            field=models.ForeignKey(default='2', help_text='Přiřaďte vybaveni', on_delete=django.db.models.deletion.CASCADE, to='hotel_reservation.vybaveni'),
        ),
    ]
