# Generated by Django 4.0.4 on 2022-06-05 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='cas_vyhotoveni',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 18, 37, 57, 679987), help_text='Prosím zadejte čas vyhodnocení', null=True, verbose_name='Čas vyhotovení'),
        ),
    ]
