# Generated by Django 4.0.4 on 2022-06-05 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0002_alter_rezervace_cas_vyhotoveni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='cas_vyhotoveni',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 18, 49, 30, 190953), help_text='Prosím zadejte čas vyhodnocení', null=True, verbose_name='Čas vyhotovení'),
        ),
    ]
