# Generated by Django 4.0.4 on 2022-06-05 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0003_alter_rezervace_cas_vyhotoveni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='cas_vyhotoveni',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 21, 0, 24, 235574), help_text='Prosím zadejte čas vyhodnocení', null=True, verbose_name='Čas vyhotovení'),
        ),
    ]
